apiVersion: apps/v1
kind: Deployment
metadata:
  name: cube-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cube-frontend
  template:
    metadata:
      labels:
        app: cube-frontend
    spec:
      containers:
      - name: cube-frontend
        image: ghcr.io/hashgo44/cube-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cube-frontend-service
spec:
  selector:
    app: cube-frontend
  ports:
    - protocol: TCP
      port: 90
      targetPort: 3000